// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Entity.Models;

public partial class EntityStartContext : DbContext
{
    public EntityStartContext(DbContextOptions<EntityStartContext> options)
        : base(options)
    {
    }

    public virtual DbSet<note> notes { get; set; }

    public virtual DbSet<user> users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<note>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__notes__3213E83FF96BB82B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}